### ISSUE TITLE
Logout from Iotum should redirect to Crexendo-Portal

### ISSUE THREAD

**Issue by rohitv1611** [iotum/community#10]
WP-1876 - Logout from Iotum should redirect to Crexendo-Portal

Crexendo portal users don’t use “Email/Password“ to log in to Iotum porta.
So when a user logout from the Iotum portal, it must be redirected to the Crexendo Portal.

Please refer to the attached screen recording.

https://github.com/user-attachments/assets/0cb09527-8a6c-49ef-afc5-ac03297cf74c

**Comment by noamtiotum** [comment]
We are going to address this.

**Comment by noamtiotum** [comment]
You can no longer log out from the Iotum app directly.  The intention will be for the Netsapiens platform to use an API to logout the user of the Iotum platform when the user logouts of the Netsapiens platform.
