### ISSUE TITLE
Poll Options are not selectable in the meeting.

### ISSUE THREAD

**Issue by rohitv1611** [iotum/community#11]
WP-1883 - Poll Options are not selectable in the meeting.
Steps:
1. Schedule a meeting and add Polls.
2. Participants join the meeting and open the polls.
3. Not able to select any option from the polls. But the Launch button still works.

**Comment by noamtiotum** [comment]
@rohitv1611 I've tried to reproduce this but I can't. Can you add screenshots or a screen capture?

Here's what I did


https://github.com/user-attachments/assets/23d193c0-3d66-4811-99e1-af22543b1465

**Comment by noamtiotum** [comment]
@rohitv1611 can you try to reproduce this issue again and post screenshots?

**Comment by rverma-1611** [comment]
@noamtiotum 
We are no longer able to reproduce this issue. You can go ahead and close the ticket.
