### ISSUE TITLE
Host unable to edit meeting if any invitee has same email as the host

### ISSUE THREAD

**Issue by rohitv1611** [iotum/community#12]
WP-1885 Host unable to edit meeting if any invitee has same email as the host

The meetings are missing the edit/preview/cancel options if any invitees have the same email as the host. 
This can cause problems with larger meetings where the host might share email with an attendee.

Image reference 
![image](https://github.com/user-attachments/assets/512ed9aa-4faf-4eb4-b4ac-eed9b220919b)

**Comment by noamtiotum** [comment]
This is confirmed and we are going to fix it.

**Comment by sara-iotum** [comment]
@rohitv1611  This has been resolved as of 11 AM ET, 7 November 2024.
