### ISSUE TITLE
Participants don't get email updates when editing meeting mode, polls, default recording preference, automatically record and dial-in numbers

### ISSUE THREAD

**Issue by rohitv1611** [iotum/community#13]
updates when editing the following meeting features,
1. meeting mode
2. polls
3. default recording preference
4. automatically record
5. dial-in numbers

I think the participants must be notified if the Dial-In Number for the meeting is updated.

**Comment by noamtiotum** [comment]
@rohitv1611 these is intentional because those are specific host settings and not applicable to participants.

If the time/change or participant list changes we do send updates to them

**Comment by noamtiotum** [comment]
@rohitv1611 

The dial-in numbers selected is just a customization to the invitation and doesn't change which dial-in numbers are available. We don't consider it an edit to the meeting that requires notifying existing participants.

**Comment by rverma-1611** [comment]
@noamtiotum 
Are you saying that the previous dial-in number will remain functional even if the user updates the dial-in number for the meeting? If that's the case, you can go ahead and close the issue.

**Comment by noamtiotum** [comment]
@rohitv1611 that's correct.
