### ISSUE TITLE
Only the first email address is updated to iotum side when the contact has multiple email addresses on NS side.

### ISSUE THREAD

**Issue by rohitv1611** [iotum/community#14]
We discussed this in our meeting on 4th September 2024. Multiple emails are not supported in the Iotum platform.
I am creating this issue just for reference.

WP-1895 - Only the first email address is updated to iotum side when the contact has multiple email addresses on NS side.

Only the first email address is updated to iotum side when the contact has multiple email addresses on NS side.

![image](https://github.com/user-attachments/assets/d3b474d8-ffd1-4932-b5c1-ddee60f984c1)

**Comment by noamtiotum** [comment]
@rohitv1611 Our plan for now is to continue to only support one email address on a contact.
