### ISSUE TITLE
Unsubscribing from plan leaves hosts "unassigned"

### ISSUE THREAD

**Issue by c1wei** [iotum/community#15]
When hosts are on planA, but then company later on gets unsub'd from planA, then those hosts are automatically put to UnAssigned and cannot use their video anymore.

Is there any way to have those hosts have a fallback plan to one of the other chosen plans?

**Comment by c1wei** [comment]
Adding screenshots here for more detail:

![Screenshot 2024-09-05 at 10 15 30 AM](https://github.com/user-attachments/assets/d4a88dd0-fd73-457c-b53d-3bc48f704be2)
The company has Basic, Pro, Pro Beta

![Screenshot 2024-09-05 at 10 15 45 AM](https://github.com/user-attachments/assets/82ecb744-a1d8-4edf-8b5a-f8b945201601)
Several of the Hosts are sub'd to Basic

![Screenshot 2024-09-05 at 10 15 34 AM](https://github.com/user-attachments/assets/f87db09e-e1e8-4f76-ae1e-ee4a91fbe79d)
I remove the subscription for Basic on the company

![Screenshot 2024-09-05 at 10 16 08 AM](https://github.com/user-attachments/assets/08b48f95-7ee4-4b73-b100-0f3d3c9d018f)
Those same hosts are made to be "unassigned"

**Comment by sara-iotum** [comment]
@c1wei The solution we propose is as follows:
- When using `/enterprise_api/subscription/cancel` an additional optional request will be provided where you can add in the plan where you would like users to be moved to
- If the option is left empty, any host that was assigned to the plan that is removed will now be unassigned

**Comment by sara-iotum** [comment]
Deployed September 26th v2.6.328

- When using `/enterprise_api/subscription/cancel` an additional optional param can be provided `"replacement_slug": "(slug)"` Note that this works only when a subscription to a **plan** is being canceled
- If the new replacement_slug option is not included in the API call, any host that was assigned to the plan that is removed will now be unassigned

**Comment by c1wei** [comment]
Thank you Sara. i've implemented this change and confirmed that the plan swtiches for hosts that would have been previously left "unassigned"

**Comment by sara-iotum** [comment]
Brilliant! Thanks for confirming.
