### ISSUE TITLE
Openning a new iotum portal/video tab causes webphone sdk to go blank

### ISSUE THREAD

**Issue by alighterink** [iotum/community#16]
With webphone open and an active Iotum subscription navivating to an iotum tab causes the webphone widget to go blank.

1)open webphone and verify sdk widget is properly rendered.
2) click "Start Meeting" in the widget or select 'Premium Video' from the App menu at the top right
3) the browser will open a new tab and navigate away from webphone. Upon returning to webphone the widget will be blank.

![image](https://github.com/user-attachments/assets/aef9bb49-7698-4365-be63-eefc2b8a74da)

**Comment by noamtiotum** [comment]
@alighterink this is not reproducible in the https://awqacore01.crexendocloud.com/ environment

Are you able to see the difference between the environment you are testing in and  https://awqacore01.crexendocloud.com/ ?

**Comment by alighterink** [comment]
@noamtiotum Its reproducible on the https://awqacore02.netsapiens.com/webphone/video server. Its in the same cluster, but has a different hostname. Looks like once a new Iotum tab is openned then navigating back to webphone causes a 401 for the initial ping and the widget goes blank.

https://github.com/user-attachments/assets/e6aa42eb-a22a-4b0b-b421-08f83ae8d441

**Comment by noamtiotum** [comment]
@alighterink Are you guys able to see why there would be a difference in behaviour between your two servers?

Based on the screen cast you've shared my guess is that the widget is logged in as one user but when you launch the app you're using a different user's SSO credentials essentially logging out the widget user.  

Maybe we can get access to this server so we can try it ourselves, or you could also try capturing the SSO credentials of the widget and the stand-alone app to see if they are different for some reason.

**Comment by noamtiotum** [comment]
@alighterink Brandon got us access to https://awqacore02.netsapiens.com/webphone/video and we're able to reproduce what you are seeing. 

We're trying to debug it.

**Comment by noamtiotum** [comment]
@alighterink we found the root cause and are fixing it!

**Comment by noamtiotum** [comment]
This has been resolved.
