### ISSUE TITLE
Launching the standalone web app into a new window/tab from widget page becomes widget not standalone app

### ISSUE THREAD

**Issue by noamtiotum** [iotum/community#17]
**Describe the bug**
If our widget is running in the parent page of a partner app, for example Netsapiens webphone and from the webphone they launch our standalone app in a new tab, the new tab renders as a widget and not as the standalone app.  

**To Reproduce**
1. Go to the Netsapiens webphone
2. Click on the video tab
3. Click on the apps menu and select "premium video"
4. See that the new tab renders as the widget and is missing the tabs at the top

https://github.com/user-attachments/assets/454aa352-d551-4954-a68f-54eb447e78ca

**Expected behavior**
The new tab should render as the standalone app, tab navigation visible at the top of the page

**Desktop (please complete the following information):**
Browser and OS independant

**Comment by jerry2013** [comment]
FYI, regarding how to implement open full app function (either `<a target>` or `window.open`)

example code: https://github.com/iotum/iotum-samples/blob/c99f6b9b05997c9b680fdcc171dfba12fc6dcdad/src/components/OpenFullAppButton.jsx#L11

- the `events=false` is used to ensure the new app tab/window does not inherit the widget state
- optionally, `noreferrer` can be set as a hint to indicate full app

**Comment by alighterink** [comment]
@noamtiotum is this expected to be fix in production? We are not seeing an error when running of the staging server

**Comment by noamtiotum** [comment]
> @noamtiotum is this expected to be fix in production? We are not seeing an error when running of the staging server

@alighterink Can you post a screen shot of what you're seeing. It's working on the staging to staging accounts I have 1005@iotumstaging
