### ISSUE TITLE
Webapp fails to resume polling for upcoming meetings after sleep/wake

### ISSUE THREAD

**Issue by catejust** [iotum/community#18]
Observed through v2.6.326

I typically leave the "meet" tab open in my browser ( _https://URL.com/conf/conferences/create_ ) and the webapp seems to poll for two resources periodically

- /accounts/ping every few minutes
- /conf/list_upcoming every hour or so, with list_upcoming used to show my upcoming meetings "today"

I've noticed that when I move my computer between home and work, the webapp will resume polling for /accounts/ping, but will not automatically resume polling for /conf/list_upcoming

As a result, the "meet" tab will fail to show me that I have an upcoming meeting today unless I switch between the "Past"/"Today"/"Upcoming" tabs, or refresh the page. 

It would be nice if the app could resume polling for list_upcoming on its own in order to always show an accurate list of upcoming meetings without the need for user intervention.

**Comment by jerry2013** [comment]
issue confirmed. will fix.

**Comment by sara-iotum** [comment]
Deployed September 12th v2.6.327
