### ISSUE TITLE
host/fetch_all api requested is taking to long

### ISSUE THREAD

**Issue by rverma-1611** [iotum/community#20]
We experienced a very slow response for host/fetch_all API request. Sometimes it takes ~30sec to get a response.

Login as a Super User or Reseller to a large domain which has more than 100 users, Login to the portal takes longer than usual.
In our API logs, we saw that it took very long to get the response for 'host/fetch_all' from Iotum server.

The system logs are overwritten. We experience this issue on 9th September 2024.
I will collect the logs again and attach here.

**Comment by sara-iotum** [comment]
Deployed September 26th v2.6.328
