### ISSUE TITLE
Cannot create contact with same email as an existing host

### ISSUE THREAD

**Issue by noamtiotum** [iotum/community#23]
### Discussed in https://github.com/iotum/community/discussions/21

<div type='discussions-op-text'>

<sup>Originally posted by **c1wei** August 29, 2024</sup>
My host (HostA) has another coworker host (HostB) that has email "email_redacted@email.com"

If my HostA tries to add a contact with "email_redacted@email.com" this will not create a new contact, and instead respond with the HostB data. This is being done via contact/create Iotum API endpoint.</div>

**Comment by sara-iotum** [comment]
Deployed September 26th v2.6.328

We will show the username on the participant page when scheduling and on the preview page after confirming scheduling.
