### ISSUE TITLE
[BUG] Loading Meeting page when already on Meeting Service doesnt reset to join meeting view

### ISSUE THREAD

**Issue by alighterink** [iotum/community#25]
**Describe the bug**
Within our integration when navigated back into the Video subpage we load the Meet service. This normally resets the widge view to see the dashboard. However the bug is that if a user has clicked on the Join Meeting button and has the feild to enter a meeting number, navigating our app to another subpage and back is not resetting the Meeting service, despite the .load(meett) is being called.

**To Reproduce**
1. In NS webphone click the Video subpage
2. Click join meeting button
3. Click a different Subpage to navigate to, (ie. contacts)
4.  Click back to Video subpage and notice the Join Meeting is still shown.

**Expected behavior**
Its expected the the default Meet view will be shown when calling .load(meet)

**Comment by sara-iotum** [comment]
Hi @alighterink we've talked over this one as a team and believe that this is the correct user experience in this case. I think that it would be expected that the user returns to the same screen they had previously navigated to. Otherwise the app would essentially be reloaded.
