### ISSUE TITLE
[BUG] Widget card getting refused to connect error

### ISSUE THREAD

**Issue by rverma-1611** [iotum/community#26]
**Describe the bug**
Widget card getting refused to connect error

**To Reproduce**
1. Go to the Webphone
2. Click on the Video sidebar
3. Click on the "Add Card to Grid" icon
4. Closed the Card and create the card multiple time 
5. You will get refused to connect error.

**Expected behavior**
You should never see the refused to connect error

**Screenshots**
On https://qa-u20-tor9.netsapiens.com with Iotum's production server
you will see the "refused to connect error" at 0:03 timestamp in the recording.
Here is the screen recording:

https://github.com/user-attachments/assets/a71265a9-6c97-48cf-b28d-6304ad08e1ff

On https://awqacore01.crexendocloud.com/ with Iotum staging server, the issue is intermittent
you will see the "refused to connect error" at 0:13 timestamp in the recording.
Here is the screen recording:

https://github.com/user-attachments/assets/b45ca718-ff08-4640-b39f-230f10ccfe99

**Comment by noamtiotum** [comment]
This has been resolved.
