### ISSUE TITLE
[BUG] md_format not consistent on different tabs in iotum video tab in webphone.

### ISSUE THREAD

**Issue by jshen-netsapiens** [iotum/community#27]
With md_format set to "D M" I would expect that all date formats should be day month but in most pages it's still showing up as the default "M D"

1. Set user md_format to "D M" via API
2. Open Webphone and navigate to video tab
3. Schedule Meeting
4. Observe dates shown are in "M D" format
5. Go to Past and Upcoming Tab
6. Observe dates shown are in "M D" format

Expected behavior
Dates should be shown in "D M" format

**Screenshots**
![image](https://github.com/user-attachments/assets/e7ec5be2-05b5-44f0-86f6-a217e3c4690d)
![image](https://github.com/user-attachments/assets/5ec5f5ba-9dec-4a20-bee5-69fe46c74fb2)
![image](https://github.com/user-attachments/assets/eab1ed9b-0bcc-4317-b4eb-0c20dc019637)

 - OS: Windows 11
 - Browser Chrome 128.0.6613.85 (Official Build) (64-bit)

**Comment by noamtiotum** [comment]
@dustructer our QA team is attempting to replicate this.

**Comment by sara-iotum** [comment]
@dustructer We have replicated this issue and have a bug ticket open on our side to fix this

**Comment by sara-iotum** [comment]
@dustructer This has been resolved as of 11 AM ET, 7 November 2024.
