### ISSUE TITLE
[BUG] Read company request got 500 Internal Server Error when reading a newly created company without hosts

### ISSUE THREAD

**Issue by GoGoAlalei** [iotum/community#28]
**Describe the bug**
Read company request got 500 Internal Server Error when reading a newly created company without hosts.

**To Reproduce**
1. Create a new NS domain and enable the premium video and save.
2. Do not add any users/hosts to the domain/company.
3. Read the company from Iotum associated with the NS domain.
     curl --location --request GET 'https://qa-u22-tor4.netsapiens.com/ns-api/v2/domains/lyy9/video' \
4. The request got 500 error code.
     {
    "error_code": 500,
    "status-message": "Internal Server Error"
      }
5. Once hosts are added to the company. Read company will respond with the correct info.

**Expected behavior**
The new company even without hosts should be readable.

**Comment by jerry2013** [comment]
but that's not our server.

**Comment by noamtiotum** [comment]
@Anitaiotum @sara-iotum can you try to reproduce the following with out API, Netsapiens is just passing through the 500 from our platform

1. Create a company `/enterprise_api/company/create`
2. Fetch the company `/enterprise_api/company/fetch`

**Comment by sara-iotum** [comment]
@GoGoAlalei This bug has been fixed with our deployment this morning.
