### ISSUE TITLE
Configure crexendo deployment setting which creates a new unique meeting ID for every new meeting.

### ISSUE THREAD

**Issue by jshen-netsapiens** [iotum/community#29]
As title suggests we would like to deploy with the setting for unique meeting id turned on.

**Comment by sara-iotum** [comment]
@dustructer I am assuming you mean the 'Random Access Code' feature (sometimes referred to as the 'one-time' code in the API documentation). See the following support article for reference:

https://support.meet.netsapiens.com/en/support/solutions/articles/42000076399-security-settings-random-access-code-and-security-passcodes

If that is the case, can you confirm if you want this the default for ALL child domains (sub-resellers)? Or is this only for Crexendo VIP and meet.netsapiens?

**Comment by noamtiotum** [comment]
@sara-iotum please make this the default for all new WLs period.  

We should discuss if we can update that setting for all existing NS WL and Hosts that have arleady been created.

**Comment by sara-iotum** [comment]
@dustructer This has been done as of around 11 AM ET, 7 November 2024.
