### ISSUE TITLE
Not able to create a specific company. Getting false "Subdomain has already been taken"

### ISSUE THREAD

**Issue by c1wei** [iotum/community#3]
Issue: 400 Error "Subdomain has already been taken" when Creating a Company

I’m trying to create a specific company, but I keep getting a 400 error with the message “Subdomain has already been taken.” However, when I list all the companies, I don’t see this subdomain.

Request to Create Company:

https://app.meet.crexendocloud.com/enterprise_api/company/create
Payload: {"subdomain":"cwei6","name":"cwei6","partner_id":"cwei6","auth_token":"[hidden]"}

Request to List Companies:

https://app.meet.crexendocloud.com/enterprise_api/company/fetch_all
Payload: {"auth_token":"[hidden]"}

The list of companies I receive does not include any with the subdomain cwei6, nor do I see any cwei6 company in the iotum portal. Has anyone else experienced this issue or knows a workaround?

**Comment by chris-iotum** [comment]
We investigated and there is a deleted company with the subdomain `cwei6`, and that it shows if `"show_deleted": true` is included in the `/company/fetch_all` request. We currently consider even deleted accounts in enforcing the uniqueness of subdomains. We're discussing the implications of limiting that uniqueness check to only undeleted accounts.

**Comment by sara-iotum** [comment]
@c1wei we are going to change the subdomain for a deleted company to add the word `deleted-[somedigits]` so that it will be possible for a new company to be created with the previous domain. i.e. `cwei6` becomes `cwei6-deleted-987654`

**Comment by sara-iotum** [comment]
For internal reference: https://github.com/iotum/facetalk/pull/9335

**Comment by chris-iotum** [comment]
The fix for this has been deployed.
