### ISSUE TITLE
[BUG] Creating Meet widget with Past/Upcoming hidden (hidden: 53) should respect when view more

### ISSUE THREAD

**Issue by alighterink** [iotum/community#30]
**Describe the bug**
WHen creatinga Meeting widget for the small UI card view the hiddenElement 53 is passed in. However when >4 meetings have been scheduled for the day a "view all" button appears a the bottom. Clicking this button does not inherrit the hiddenElement [53] and the Past/Upcoming meetings are shown. This because an issue when the user tries to edit the meeting. Which sends a "dashboard.NAVIGATE_TO_SCHEDULE" event.

**To Reproduce**
Create multiple meetings for same day (4+)
Open Video Card
Scroll to bottom of card and click "view all"
Past/Upcoming meeting are shown & edit button doesnt edit correct meeting instance.

**Expected behavior**
Past/Upcoming meetings should not be show, only the "todays" meetings
The edit button should not appear, or when click should trigger correct meeting instance to edit in Scheduler menu.

**Screenshots**
![image](https://github.com/user-attachments/assets/0955a7df-fae0-4a7e-927d-207962cc62bc)
![image](https://github.com/user-attachments/assets/4438a788-6538-4cbb-95cf-9bf9737dace5)

**Additional context**
Netsapiens @ Iotum integration

**Comment by sara-iotum** [comment]
Thanks @alighterink I'll bring this up with the team to figure out a solution

**Comment by sara-iotum** [comment]
@alighterink This has been resolved as of 11 AM ET, 7 November 2024.
All of today's meetings will now display (instead of the previous limit of 4) with no link to past or upcoming.
