### ISSUE TITLE
SDK Ping returning 401 causing blank screen

### ISSUE THREAD

**Issue by alighterink** [iotum/community#5]
Launching the sdk with valid credentials and leaving the page open for some time (roughly 1 hour in testing) pings will start to receive 401 which causues the SDK to hide itself.
![image](https://github.com/user-attachments/assets/573340b3-bc4d-43e8-8840-fa476583498d)
![image](https://github.com/user-attachments/assets/1436bb99-da54-4fa4-a9ee-1de447b11b24)

If this is a common issue with credentials being denied, can get an SDK event emitted so that we can refetch valid credentials and reload the SDK?

**Comment by jerry2013** [comment]
I'm unable to repro the issue using the sample apps.

steps:
- log out from account on the target domain
- load dashboard sample app, load "meetings"
- switch to a different tab
- wait for ~ 1.5 hrs
- go back to the tab
- ping check succeeds and the widget function resumes

can you PM me the full network capture?

**Comment by sara-iotum** [comment]
From Andrew:

> Our testers have run into it a few times. Not easily reproducible, but when it happens its a poor UX experience with the whole tab going blank and only refreshing the whole page to get the video subpage back. As i mentioned in the bottom of the ticket, could get have event to listen for if such events occur and we can at least provide some message rather than a blank screen.

**Comment by noamtiotum** [comment]
@jerry2013 @alighterink see this comment https://github.com/iotum/community/issues/9#issuecomment-2332011283

I think this applies to this situation. I believe we could fire an event on a 401 and the parent page could handle that however they want.

**Comment by noamtiotum** [comment]
@alighterink the 401s are a bug on our end related to session management on our end, same problem as https://github.com/iotum/community/issues/16 

So those shouldn't happen once we fix it. 

We are also going to emit an event if the user is signed out for any reason.

**Comment by jerry2013** [comment]
FYI - coming to this week's release.

- a new event `dashboard.SESSION_EXPIRED` will be emitted for this case.
  - for code sample, see https://github.com/iotum/iotum-samples/pull/56.
- there is an existing event `dashboard.UNLOAD` already for this case, when the widget unloads itself after the session expired.
  - I forgot to list this event in the widget sdk doc, which I'll address together with the new event.
  - after the release, `UNLOAD` happens after `SESSION_EXPIRED`

**Comment by jerry2013** [comment]
This has been released.

The [Callbridge SDK](https://github.com/iotum/callbridge-js) package will be updated at a later time to document the events in code completion and wiki. The function itself is compatible with the current SDK.
