### ISSUE TITLE
Initial login shows Term & Conditions priviacy policy page

### ISSUE THREAD

**Issue by alighterink** [iotum/community#8]
When creating a widget with newly created Host that has not logged into the Iotum portal. The subpage shows a full screen Term and Conditions page that is above our UI and not hideable.

![image](https://github.com/user-attachments/assets/206aedd9-7201-4be7-91c0-f5e6f81daba7)

**Comment by noamtiotum** [comment]
@alighterink I've tried to reproduce this and do see the terms and conditions modal but it is not hiding any of your UI and is usable and readable by the user. Here's a screen a screen recording of what I see

https://github.com/user-attachments/assets/0b162d71-5cc8-40e1-bb30-51fddded4d2e

**Comment by noamtiotum** [comment]
@alighterink we're going to hide the terms and conditions for your users. however I think the "bug" isn't related to the terms and conditions being displayed but rather the position of the widget where it shouldn't be

I'm not able to reproduce it on the https://awqacore01.crexendocloud.com/portal/home

**Comment by jerry2013** [comment]
I'm also not able to repro by loading `/webphone` and waiting there.

Based on your screenshot above, it means that the "contact" flexbox is not filling the space correctly.

@alighterink You need to have `overflow:hidden` on the `<main>` tag to prevent the section from moving (e.g. when adding extra email addresses to a contact).

-|-
-|-
![image](https://github.com/user-attachments/assets/a34bff46-a7c9-439a-9f92-e6198125236e)|![image](https://github.com/user-attachments/assets/7a5facb9-3571-406d-af97-122f0878bca9)
![image](https://github.com/user-attachments/assets/8c92952f-9bbd-41a9-a077-1fb6c08acf37)|![image](https://github.com/user-attachments/assets/bd9e2a4a-ace0-475a-8366-785fe7839874)

**Comment by noamtiotum** [comment]
We are going to remove the terms and conditions overlay for users created via API like your case.

**Comment by sara-iotum** [comment]
Deployed September 26th Release v2.6.328
