### ISSUE TITLE
Widget shown as logged out in card

### ISSUE THREAD

**Issue by alighterink** [iotum/community#9]
Frequently on when opening a smaller widget it will appear to be logged out. The widget is initialized with the same credentials that the larger subpage widget uses.
![image](https://github.com/user-attachments/assets/87ea9a77-7552-4ea0-9021-e6b293f8085a)

attached is a har file with the network requests
~~loggedout_card.har~~ (removed due to containing secrets)

**Comment by jerry2013** [comment]
based on the network trace, I've a feeling that this is caused by 2 simultaneous SSO sessions being issued. I'll try to simulate your usage here.

in the meantime, a possible workaround is to wait for the widget-1's init/load event before creating the widget-2.

**Comment by noamtiotum** [comment]
I am not able to reproduce this however, I am able to cause a similar outcome by doing the following:

1. go to the web phone, click on the meetings tab. Iotum widget appears correctly.
2. Open the standalone Iotum app through the Apps menu in the webphone
3. In in the stand alone meetings app, Logout
4. The meeting widgets in the web phone are now just blank white. See the sreenshot.

This would also apply to the https://github.com/iotum/community/issues/5

![image](https://github.com/user-attachments/assets/d51bd7b4-6443-4a1c-8c07-f329ccb646f3)

**Comment by noamtiotum** [comment]
@alighterink we've tracked down the why this is happening, another problem related to the parent domain not being the same as the widget iframe...

**Comment by noamtiotum** [comment]
We are going to fix this.

**Comment by jerry2013** [comment]
I think this is necessary: create widget-2 AFTER receiving the widget-1's init/load event.

here's an example: https://github.com/iotum/iotum-samples/blob/ea84b9af8e6598593c5b3e9b3018ae8d47d6ff59/src/pages/tabbed-dashboard/App.jsx#L148

**Comment by alighterink** [comment]
@jerry2013 Is there a way to change the container for the ChatWidgetRef without having to re-render the Dashboard with a new container reference?

**Comment by jerry2013** [comment]
> @jerry2013 Is there a way to change the container for the ChatWidgetRef without having to re-render the Dashboard with a new container reference?

Given how DOM works, I think this should work (I haven't tested the code)

```html
<div id="nyc"> <div id="container"></div> </div>
<div id="bos></div>
```

```js
const widget = new Callbridge.Dashboard({ ... container: '#container' ...});
widget.on('dashboard.READY', () => {
  document.getElementById('bos').appendChild(document.getElementById('container'))
});

```

**Comment by noamtiotum** [comment]
This has been resolved.
